# Generated by Django 3.2.9 on 2021-12-07 22:46

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_image', validators=[authapp.models.MaxSizeValidator(4)]),
        ),
    ]
