# Generated by Django 3.2.9 on 2021-12-08 00:02

from django.db import migrations, models
import mainapp.mixin


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_image', validators=[mainapp.mixin.MaxSizeValidator(2)]),
        ),
    ]
