# Generated by Django 3.2.9 on 2021-12-13 00:49

from django.db import migrations, models
import mainapp.mixin


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_image', validators=[mainapp.mixin.MaxSizeValidator(2)]),
        ),
    ]
