# Generated by Django 3.2.9 on 2021-12-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
