# Generated by Django 3.2.9 on 2022-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
    ]
