# Generated by Django 3.2.9 on 2021-12-09 01:04

from django.db import migrations, models
import mainapp.mixin


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_image', validators=[mainapp.mixin.MaxSizeValidator(2)], verbose_name='Аватар'),
        ),
    ]
