# Generated by Django 3.2.9 on 2022-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_userprofile_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, default='Русский', max_length=10, verbose_name='Язык'),
        ),
    ]
